Add webSocketManagerConfig types
amazon-connect/amazon-connect-chatjs pull request #161
Opened 2023-04-26 16:20 UTC by WRiferreiro

*Issue #, if available:*

As part of #153 React native support was added, one the requirements to get it to work is to override the default network online check in the global config, but they types for the config params weren't updated.

*Description of changes:*

Update the `ChatGlobalConfig` interface by adding `webSocketManagerConfig`.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2023-04-26 23:01 UTC, spencerlepine commented on src/index.d.ts
> +    /** The ws manager configuration. */
Can we re-word this to the following:

```
/**
  * Optional global configuration for the webSocketManager.
  */
```

2023-04-26 23:10 UTC, spencerlepine requested changes

2023-04-26 23:10 UTC, spencerlepine commented on src/index.d.ts
> +      /** The current network status */
Can we re-word this similar to the following as well:

```js
/**
 * Custom util function (synchronous) to check `networkIsConnected` status
 *  - Used in websocket connection heartbeat
 *  - Store update boolean value in outer scope, and pass into ChatJS (e.g. native mobile network check in React Native application)
 * 
 * @default: () => navigator.onLine; // https://developer.mozilla.org/en-US/docs/Web/API/Navigator/onLine
 */
```

2023-04-26 23:10 UTC, spencerlepine commented on src/index.d.ts
> +    /** The ws manager configuration. */
Can we re-word this similar to the following:

```js
/**
 * Optional global configuration for the webSocketManager.
 */
```

2023-04-27 18:41 UTC, spencerlepine approved these changes

2023-05-02 19:49 UTC, xiajon-amzn approved these changes

2023-05-02 19:57 UTC, spencerlepine commented
Hi @WRiferreiro, thank you for your contribution! This change will be included when the next release (`1.5.2`) is ready to be published.

Thanks, Spencer

2023-05-02 19:58 UTC, merged