Deep Heartbeat GA: update WebSocketManager to enable Blitz Chat widge…
amazon-connect/amazon-connect-chatjs pull request #198
Opened 2023-10-10 15:03 UTC by ShanshanXu2021

*Issue #, if available:*
Deep Heartbeat GA: update WebSocketManager library to enable Blitz Chat Widget users

*Description of changes:*
Deep Heartbeat is a feature implemented on WebSocketManager level to monitor agent availability in real time, so that stale connection can be closed when an agent is offline and customers can be routed to another available agent. 

Deep Heartbeat does not introduce change on Chat widget itself. It's already available to default CCP, Agent Chat UI and Customer Chat UI(deployed through LilyCustomerChatWidget Pipeline) users. The feature has CSM on CCP side, integration tests and canaries on Torii side. 

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2023-10-10 18:00 UTC, spencerlepine requested changes
Can you confirm that you have tested changes on this code base to verify ChatJS did not break?

Also can we bump the version number and update these files:
- package.json
- package-lock.json
- CHANGELOG.md

2023-10-12 20:41 UTC, spencerlepine commented on CHANGELOG.md
> +- Updated amazon-connect-websocket-manager.js library to enable Deep Heartbeat change for Blitz Chat widget users.
nit: could we remove "Blitz" team name

2023-10-12 20:41 UTC, spencerlepine approved these changes

2023-10-13 19:02 UTC, haomingli2020 approved these changes

2023-10-13 19:04 UTC, merged